pub struct TetrisStartEvent {}
pub struct TetrisGameoverDetectResultEvent {}
pub struct TetrisLineDetectResultEvent {}
pub struct TetrisGamesetEvent {}
pub struct TetrisEndedEvent {}
pub struct TetriminoSpawnRequestEvent {}
pub struct TetriminoSpawnResultEvent {}
pub struct TetriminoOnPlaceEvent {}
pub struct TetriminoRotateRequestEvent {}
pub struct TetriminoRotateResultEvent {}
pub struct TetriminoMoveStartEvent {}
pub struct TetriminoMoveEndEvent {}
pub struct TetriminoMoveResultEvent {}
pub struct TetriminoSoftdropStartEvent {}
pub struct TetriminoSoftdropEndEvent {}
pub struct TetriminoHarddropRequestEvent {}
pub struct TetriminoFallResultEvent {}
pub struct TetriminoHoldRequestEvent {}
pub struct TetriminoHoldResultEvent {}
