pub struct LocalHistory {}
pub struct LocalFuture {}
pub struct Block {}
pub enum BlockPattern {}
pub enum TetriminoType {}
pub enum Direction {}
pub struct Blocks {}
pub struct Tetrimino {}
pub struct GameId {}
pub struct LocalField {}
